spring:
  application:
    name: twitter-to-kafka-service
  profiles:
    active: twitter_to_kafka
  config:
    import: 'configserver:'
  cloud:
    config:
      name: twitter-to-kafka-service,config-client
      uri: http://localhost:8888
      username: spring_cloud_user
#      password: ENC(HNq+d430z8g+zDFbALRJjw37QSvtgwiGEPmaqaWxlqUlFQjb2+wtLjsSArygjEHt)
      password: password

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}