server:
  port: 8888

loggin:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG # can see all the details about the config server in the log output

# Required in case of loading configuration in bootstrap phase (which has priority over application.yml)
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DeluxeViper/spring-cloud-config-server-repository
          username: DeluxeViper
          password: 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
          clone-on-start: true # clone the repository on start
          default-label: main

    fail-fast: true # if config server cannot reach the config-server-repository it will stop immediately

  security:
    user:
      name: spring_cloud_user
      password: springCloud_Pwd!